require 'chef_metal'
require 'chef_metal_aws/aws_driver'
require 'chef/resource/aws_sqs_queue'
require 'chef/provider/aws_sqs_queue'
require 'chef/resource/aws_sns_topic'
require 'chef/provider/aws_sns_topic'
